---
language: node_js
node_js:
  - "4.2"

sudo: false

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-1.11.X
  - EMBER_TRY_SCENARIO=ember-1.12.X
  - EMBER_TRY_SCENARIO=ember-1.13.X
  - EMBER_TRY_SCENARIO=ember-2.0.X
  - EMBER_TRY_SCENARIO=ember-2.1.X
  - EMBER_TRY_SCENARIO=ember-2.2.X
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-1.11.X
    - env: EMBER_TRY_SCENARIO=ember-1.12.X
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
